// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/comment.ts";
import * as $1 from "./routes/api/subscribe.ts";
import * as $2 from "./routes/blog/[slug].tsx";
import * as $3 from "./routes/blog/index.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/projects.tsx";
import * as $$0 from "./islands/Comments.tsx";
import * as $$1 from "./islands/Pond.tsx";
import * as $$2 from "./islands/Subscribe.tsx";

const manifest = {
  routes: {
    "./routes/api/comment.ts": $0,
    "./routes/api/subscribe.ts": $1,
    "./routes/blog/[slug].tsx": $2,
    "./routes/blog/index.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/projects.tsx": $5,
  },
  islands: {
    "./islands/Comments.tsx": $$0,
    "./islands/Pond.tsx": $$1,
    "./islands/Subscribe.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
